In [32]:
import pandas as pd 
import requests

In [33]:
HIVREPORT = pd.read_csv('../data/HIVREPORT.csv')

In [34]:
CASES = pd.DataFrame(HIVREPORT)

In [35]:
CASES

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640,66,2366,33.8,1.1,71,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480,66,1712,52.2,1.7,72,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153,66,622,17.6,0.6,68,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7,63,32,99999.0,99999.0,55,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4,64,22,6.4,0.1,57,1,1.4,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [36]:
CASES.isnull().values.any()

False

In [37]:
type(CASES['Borough'][0])

str

In [38]:
type(CASES['HIV diagnosis rate'][0])

numpy.float64

In [39]:
type(CASES
    )

pandas.core.frame.DataFrame

In [40]:
CASES.columns.dtype

dtype('O')

In [41]:
CASES.dtypes

Year                                  int64
Borough                              object
UHF                                  object
Gender                               object
Age                                  object
Race                                 object
HIV diagnoses                         int64
HIV diagnosis rate                  float64
Concurrent diagnoses                  int64
% linked to care within 3 months      int64
AIDS diagnoses                        int64
AIDS diagnosis rate                 float64
PLWDHI prevalence                   float64
% viral suppression                   int64
Deaths                                int64
Death rate                          float64
HIV-related death rate              float64
Non-HIV-related death rate          float64
dtype: object

In [42]:
CASES.loc[CASES['Year'] == 2015]

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
4804,2015,All,All,All,All,All,2490,34.5,443,71,1307,18.1,1.1,83,1678,9.6,99999.0,99999.0
4805,2015,All,All,Male,All,All,2007,59.1,349,72,979,28.8,1.7,84,1184,9.4,99999.0,99999.0
4806,2015,All,All,Female,All,All,441,12.6,90,70,309,8.6,0.6,81,484,10.0,99999.0,99999.0
4807,2015,All,All,Transgender,All,All,42,99999.0,4,64,19,99999.0,99999.0,74,10,14.0,99999.0,99999.0
4808,2015,All,All,Female,13 - 19,All,13,4.0,1,100,7,2.2,0.1,66,0,0.0,99999.0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [43]:
CASES_2015 = CASES[CASES['Year']==2015]

In [44]:
CASES_2015

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
4804,2015,All,All,All,All,All,2490,34.5,443,71,1307,18.1,1.1,83,1678,9.6,99999.0,99999.0
4805,2015,All,All,Male,All,All,2007,59.1,349,72,979,28.8,1.7,84,1184,9.4,99999.0,99999.0
4806,2015,All,All,Female,All,All,441,12.6,90,70,309,8.6,0.6,81,484,10.0,99999.0,99999.0
4807,2015,All,All,Transgender,All,All,42,99999.0,4,64,19,99999.0,99999.0,74,10,14.0,99999.0,99999.0
4808,2015,All,All,Female,13 - 19,All,13,4.0,1,100,7,2.2,0.1,66,0,0.0,99999.0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [45]:
CASES

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
0,2011,All,All,All,All,All,3379,48.3,640,66,2366,33.8,1.1,71,2040,13.6,5.8,7.8
1,2011,All,All,Male,All,All,2595,79.1,480,66,1712,52.2,1.7,72,1423,13.4,5.7,7.7
2,2011,All,All,Female,All,All,733,21.1,153,66,622,17.6,0.6,68,605,14.0,6.0,8.0
3,2011,All,All,Transgender,All,All,51,99999.0,7,63,32,99999.0,99999.0,55,12,11.1,5.7,5.4
4,2011,All,All,Female,13 - 19,All,47,13.6,4,64,22,6.4,0.1,57,1,1.4,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6000,2015,Staten Island,Willowbrook,Male,All,Asian/Pacific Islander,0,0.0,0,99999,0,0.0,0.1,100,0,0.0,99999.0,99999.0
6001,2015,Staten Island,Willowbrook,Male,All,Black,1,72.4,0,100,0,0.0,1.1,80,0,0.0,99999.0,99999.0
6002,2015,Staten Island,Willowbrook,Male,All,Latino/Hispanic,2,43.9,0,100,0,0.0,0.7,87,1,8.3,99999.0,99999.0
6003,2015,Staten Island,Willowbrook,Male,All,Other/Unknown,1,218.9,0,0,0,0.0,0.7,100,0,0.0,99999.0,99999.0
6004,2015,Staten Island,Willowbrook,Male,All,White,0,0.0,0,99999,0,0.0,0.2,93,0,0.0,99999.0,99999.0

In [51]:
CASES_YEARBX = CASES_2015[CASES_2015['Borough']=='Bronx']

In [52]:
CASES_YEARBX

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
4830,2015,Bronx,All,All,All,All,500,42.3,97,74,290,24.5,1.9,80,453,10.7,99999.0,99999.0
4831,2015,Bronx,All,Female,13 - 19,All,6,8.8,0,100,2,2.9,0.1,72,0,0.0,99999.0,99999.0
4832,2015,Bronx,All,Female,20 - 29,All,37,30.1,5,65,12,9.8,0.6,64,2,2.5,99999.0,99999.0
4833,2015,Bronx,All,Female,30 - 39,All,33,30.6,5,52,24,22.2,1.1,73,12,7.0,99999.0,99999.0
4834,2015,Bronx,All,Female,40 - 49,All,38,37.8,11,76,30,29.9,2.3,78,34,11.2,99999.0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5025,2015,Bronx,Pelham - Throgs Neck,Male,All,Asian/Pacific Islander,3,31.0,0,67,2,20.6,0.3,74,0,0.0,99999.0,99999.0
5026,2015,Bronx,Pelham - Throgs Neck,Male,All,Black,22,92.0,4,73,14,58.6,3.4,77,9,7.4,99999.0,99999.0
5027,2015,Bronx,Pelham - Throgs Neck,Male,All,Latino/Hispanic,23,38.4,4,65,16,26.7,1.8,83,16,7.5,99999.0,99999.0
5028,2015,Bronx,Pelham - Throgs Neck,Male,All,Other/Unknown,0,0.0,0,99999,0,0.0,0.6,100,1,86.1,99999.0,99999.0
5029,2015,Bronx,Pelham - Throgs Neck,Male,All,White,2,8.1,1,50,2,8.1,0.7,89,2,4.7,99999.0,99999.0

In [53]:
CASES_YEARBXBLK = CASES_YEARBX[CASES_YEARBX['Race']=='Black']

In [54]:
CASES_YEARBXBLK

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
4839,2015,Bronx,All,Female,All,Black,78,39.9,17,72,60,30.7,2.3,78,87,12.0,99999.0,99999.0
4851,2015,Bronx,All,Male,All,Black,161,102.9,34,77,92,58.8,4.1,77,134,11.3,99999.0,99999.0
4864,2015,Bronx,Crotona - Tremont,Female,All,Black,15,56.4,2,73,15,56.4,3.7,77,18,12.5,99999.0,99999.0
4876,2015,Bronx,Crotona - Tremont,Male,All,Black,39,171.3,5,74,9,39.5,5.8,76,28,10.5,99999.0,99999.0
4889,2015,Bronx,Fordham - Bronx Park,Female,All,Black,17,59.0,5,82,13,45.1,2.7,78,9,5.8,99999.0,99999.0
4901,2015,Bronx,Fordham - Bronx Park,Male,All,Black,27,111.3,9,81,14,57.7,5.0,79,17,7.6,99999.0,99999.0
4914,2015,Bronx,High Bridge - Morrisania,Female,All,Black,11,33.5,1,64,10,30.5,3.0,77,28,17.2,99999.0,99999.0
4926,2015,Bronx,High Bridge - Morrisania,Male,All,Black,31,114.1,7,81,21,77.3,5.4,77,44,15.7,99999.0,99999.0
4939,2015,Bronx,Hunts Point - Mott Haven,Female,All,Black,10,68.3,2,70,6,41.0,3.8,77,15,17.3,99999.0,99999.0
4952,2015,Bronx,Hunts Point - Mott Haven,Male,All,Black,19,153.9,6,68,19,153.9,6.7,73,24,17.3,99999.0,99999.0
4965,2015,Bronx,Kingsbridge - Riverdale,Female,All,Black,2,35.7,0,50,0,0.0,1.3,91,1,7.8,99999.0,99999.0
4977,2015,Bronx,Kingsbridge - Riverdale,Male,All,Black,1,25.0,0,0,1,25.0,2.6,81,2,8.0,99999.0,99999.0
4989,2015,Bronx,Northeast Bronx,Female,All,Black,11,19.5,5,64,9,15.9,1.0,82,2,2.0,99999.0,99999.0
5001,2015,Bronx,Northeast Bronx,Male,All,Black,22,52.3,3,86,14,33.3,1.8,81,10,8.5,99999.0,99999.0
5014,2015,Bronx,Pelham - Throgs Neck,Female,All,Black,12,39.7,2,75,7,23.2,1.9,80,14,13.4,99999.0,99999.0
5026,2015,Bronx,Pelham - Throgs Neck,Male,All,Black,22,92.0,4,73,14,58.6,3.4,77,9,7.4,99999.0,99999.0

In [55]:
hiv_final = CASES_YEARBXBLK[CASES_YEARBXBLK['Gender']=='Male']

In [56]:
hiv_final

,Year,Borough,UHF,Gender,Age,Race,HIV diagnoses,HIV diagnosis rate,Concurrent diagnoses,% linked to care within 3 months,AIDS diagnoses,AIDS diagnosis rate,PLWDHI prevalence,% viral suppression,Deaths,Death rate,HIV-related death rate,Non-HIV-related death rate
4851,2015,Bronx,All,Male,All,Black,161,102.9,34,77,92,58.8,4.1,77,134,11.3,99999.0,99999.0
4876,2015,Bronx,Crotona - Tremont,Male,All,Black,39,171.3,5,74,9,39.5,5.8,76,28,10.5,99999.0,99999.0
4901,2015,Bronx,Fordham - Bronx Park,Male,All,Black,27,111.3,9,81,14,57.7,5.0,79,17,7.6,99999.0,99999.0
4926,2015,Bronx,High Bridge - Morrisania,Male,All,Black,31,114.1,7,81,21,77.3,5.4,77,44,15.7,99999.0,99999.0
4952,2015,Bronx,Hunts Point - Mott Haven,Male,All,Black,19,153.9,6,68,19,153.9,6.7,73,24,17.3,99999.0,99999.0
4977,2015,Bronx,Kingsbridge - Riverdale,Male,All,Black,1,25.0,0,0,1,25.0,2.6,81,2,8.0,99999.0,99999.0
5001,2015,Bronx,Northeast Bronx,Male,All,Black,22,52.3,3,86,14,33.3,1.8,81,10,8.5,99999.0,99999.0
5026,2015,Bronx,Pelham - Throgs Neck,Male,All,Black,22,92.0,4,73,14,58.6,3.4,77,9,7.4,99999.0,99999.0

In [57]:
hiv_final.to_csv('../output/HIVFinal.csv', index=False)